#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

#source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-web" >/dev/null; then
    yunohost service remove "$app-web"
fi

if ynh_hide_warnings yunohost service status "$app-sidekiq" >/dev/null; then
    yunohost service remove "$app-sidekiq"
fi
if ynh_hide_warnings yunohost service status "$app-sidekiq-default" >/dev/null; then
    yunohost service remove "$app-sidekiq-default"
fi
if ynh_hide_warnings yunohost service status "$app-sidekiq-pull" >/dev/null; then
    yunohost service remove "$app-sidekiq-pull"
fi
if ynh_hide_warnings yunohost service status "$app-sidekiq-push" >/dev/null; then
    yunohost service remove "$app-sidekiq-push"
fi
if ynh_hide_warnings yunohost service status "$app-sidekiq-ingress" >/dev/null; then
    yunohost service remove "$app-sidekiq-ingress"
fi

if ynh_hide_warnings yunohost service status "$app-streaming" >/dev/null; then
    yunohost service remove "$app-streaming"
fi
if ynh_hide_warnings yunohost service status "$app-streaming-1" >/dev/null; then
    yunohost service remove "$app-streaming-1"
fi
if ynh_hide_warnings yunohost service status "$app-streaming-2" >/dev/null; then
    yunohost service remove "$app-streaming-2"
fi
if ynh_hide_warnings yunohost service status "$app-streaming-3" >/dev/null; then
    yunohost service remove "$app-streaming-3"
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd "$app-web"
ynh_config_remove_systemd "$app-sidekiq"
ynh_config_remove_systemd "$app-sidekiq-default"
ynh_config_remove_systemd "$app-sidekiq-pull"
ynh_config_remove_systemd "$app-sidekiq-push"
ynh_config_remove_systemd "$app-sidekiq-ingress"
ynh_config_remove_systemd "$app-streaming"
ynh_config_remove_systemd "$app-streaming-1"
ynh_config_remove_systemd "$app-streaming-2"
ynh_config_remove_systemd "$app-streaming-3"

# Remove the dedicated NGINX config
ynh_config_remove_nginx

sed -i "### MASTODON YNH EXTRAS START/,/### MASTODON YNH EXTRAS END/d" /etc/nginx/conf.d/$domain.conf

# Remove a cron file
ynh_safe_rm "/etc/cron.d/$app"

# Remote logrotate config
ynh_config_remove_logrotate

# Remove swap
#ynh_del_swap

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
